source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target :AerisSDKDemo, :exclusive => true do
	xcodeproj 'AerisSDKDemo.xcodeproj'
	pod 'GoogleMaps'
	pod 'AFNetworking'
	pod 'PAPreferences'
end