
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

inhibit_all_warnings!
use_frameworks!

workspace 'AerisDemo.xcworkspace'

def common_pods
	pod 'AerisWeather'
	pod 'AerisWeather/Maps'
	pod 'AerisWeather/Mapbox'
	pod 'AerisWeather/Google'
end

target :AerisObjCDemo do
	project 'AerisDemo.xcodeproj'
	common_pods
end

target :AerisSwiftDemo do
	project 'AerisDemo.xcodeproj'
	common_pods
end

target :AerisDemoSupport do
	project 'AerisDemoSupport/AerisDemoSupport.xcodeproj'
	common_pods
end

pre_install do |installer|
	def installer.verify_no_static_framework_transitive_dependencies; end
end