source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
inhibit_all_warnings!

target 'AerisSDKDemo' do
	project 'AerisSDKDemo.xcodeproj'
	pod 'AerisWeather'
	pod 'AerisWeather/AerisUI'
	pod 'AerisWeather/AerisMap'
	pod 'AerisWeather/AerisMapboxMap'
	pod 'AerisWeather/AerisGoogleMap'
	pod 'PAPreferences'
end