//
//  AWFLayerType.h
//  AerisMap
//
//  Created by Nicholas Shipes on 10/16/13.
//  Copyright (c) 2013 HAMweather, LLC. All rights reserved.
//

#import <Foundation/Foundation.h>

/**
 *  Options for weather layer types.
 */
typedef NS_ENUM(NSUInteger, AWFLayerType) {
	AWFLayerTypeNone = 0,
	
	// radar/sat
	AWFLayerTypeRadar,
	AWFLayerTypeRadar2m,
	AWFLayerTypeSatelliteVisible,
	AWFLayerTypeSatellite,
	AWFLayerTypeSatelliteInfraredColorUS,
	AWFLayerTypeSatelliteInfraredColor,
	AWFLayerTypeSatelliteWaterVapor,
	AWFLayerTypeSatelliteGlobal,
	AWFLayerTypeSatelliteVisibleTransparent,
	
	// forecasts
	AWFLayerTypeFutureRadarHRRR,
	AWFLayerTypeFutureRadarNAM,
	AWFLayerTypeFutureRadar,
	AWFLayerTypeFutureSatelliteHRRR,
	AWFLayerTypeFutureSatelliteNAM,
	AWFLayerTypeFutureSatelliteGFS,
	AWFLayerTypeFutureSatellite,
	AWFLayerTypeFutureTemperaturesHRRR,
	AWFLayerTypeFutureTemperaturesNAM,
	AWFLayerTypeFutureTemperaturesGFS,
	AWFLayerTypeFutureTemperaturesNDFD,
	AWFLayerTypeFutureTemperatures,
	AWFLayerTypeFuturePrecipHRRR,
	AWFLayerTypeFuturePrecipNAM,
	AWFLayerTypeFuturePrecipGFS,
	AWFLayerTypeFuturePrecip,
	AWFLayerTypeFuturePrecipIntervalsHRRR,
	AWFLayerTypeFuturePrecipIntervalsNAM,
	AWFLayerTypeFuturePrecipIntervalsGFS,
	AWFLayerTypeFuturePrecipIntervals,
	AWFLayerTypeFutureDewPointsHRRR,
	AWFLayerTypeFutureDewPointsNAM,
	AWFLayerTypeFutureDewPointsGFS,
	AWFLayerTypeFutureDewPointsNDFD,
	AWFLayerTypeFutureDewPoints,
	AWFLayerTypeFutureHumidityHRRR,
	AWFLayerTypeFutureHumidityNAM,
	AWFLayerTypeFutureHumidityGFS,
	AWFLayerTypeFutureHumidityNDFD,
	AWFLayerTypeFutureHumidity,
	AWFLayerTypeFutureWindSpeedsHRRR,
	AWFLayerTypeFutureWindSpeedsGFS,
	AWFLayerTypeFutureWindSpeedsNDFD,
	AWFLayerTypeFutureWindSpeeds,
	AWFLayerTypeFutureJetStreamHRRR,
	AWFLayerTypeFutureJetStreamGFS,
	AWFLayerTypeFutureJetStreamNAM,
	AWFLayerTypeFutureJetStream,
	AWFLayerTypeFutureWindGustsHRRR,
	AWFLayerTypeFutureWindGustsNAM4K,
	AWFLayerTypeFutureWindGustsGFS,
	AWFLayerTypeFutureWindGustsNDFD,
	AWFLayerTypeFutureWindGusts,
	AWFLayerTypeFutureFeelsLikeHRRR,
	AWFLayerTypeFutureFeelsLikeNAM,
	AWFLayerTypeFutureFeelsLikeGFS,
	AWFLayerTypeFutureFeelsLikeNDFD,
	AWFLayerTypeFutureFeelsLike,
	AWFLayerTypeFutureHeatIndexHRRR,
	AWFLayerTypeFutureHeatIndexNAM,
	AWFLayerTypeFutureHeatIndexGFS,
	AWFLayerTypeFutureHeatIndexNDFD,
	AWFLayerTypeFutureHeatIndex,
	AWFLayerTypeFutureWindChillHRRR,
	AWFLayerTypeFutureWindChillNAM,
	AWFLayerTypeFutureWindChillGFS,
	AWFLayerTypeFutureWindChillNDFD,
	AWFLayerTypeFutureWindChill,
	AWFLayerTypeFutureSnowNAM,
	AWFLayerTypeFutureSnowGFS,
	AWFLayerTypeFutureSnow,
	AWFLayerTypeFutureTemperaturesMaxNDFD,
	AWFLayerTypeFutureTemperaturesMax,
	AWFLayerTypeFutureTemperaturesMaxTextMetric,
	AWFLayerTypeFutureTemperaturesMaxTextDark,
	AWFLayerTypeFutureTemperaturesMaxTextLarge,
	AWFLayerTypeFutureTemperaturesMaxText,
	AWFLayerTypeFutureTemperaturesMinNDFD,
	AWFLayerTypeFutureTemperaturesMin,
	AWFLayerTypeFutureTemperaturesMinTextMetric,
	AWFLayerTypeFutureTemperaturesMinTextDark,
	AWFLayerTypeFutureTemperaturesMinTextLarge,
	AWFLayerTypeFutureTemperaturesMinText,
	AWFLayerTypeFutureVisibilityHRRR,
	AWFLayerTypeFutureVisibilityNAM,
	AWFLayerTypeFutureVisibility,
	AWFLayerTypeFutureRoadConditions,
	AWFLayerTypeFutureRoadConditionsMidterm,
	AWFLayerTypeFutureRoadConditionsIndex,
	AWFLayerTypeFutureRoadConditionsIndexMidterm,
	
	// severe
	AWFLayerTypeLightningStrikeDensity,
	AWFLayerTypeTropical,
	AWFLayerTypeAdvisories,
	
	// observations
	AWFLayerTypeTemperatures,
	AWFLayerTypeTemperaturesTextMetric,
	AWFLayerTypeTemperaturesTextDark,
	AWFLayerTypeTemperaturesTextLarge,
	AWFLayerTypeTemperaturesText,
	AWFLayerTypeDewPoints,
	AWFLayerTypeDewPointsTextMetric,
	AWFLayerTypeDewPointsTextDark,
	AWFLayerTypeDewPointsTextLarge,
	AWFLayerTypeDewPointsText,
	AWFLayerTypeHumidity,
	AWFLayerTypeHumidityTextDark,
	AWFLayerTypeHumidityTextLarge,
	AWFLayerTypeHumidityText,
	AWFLayerTypeWinds,
	AWFLayerTypeWindsTextDark,
	AWFLayerTypeWindsTextLarge,
	AWFLayerTypeWindsText,
	AWFLayerTypeWindGusts,
	AWFLayerTypeWindGustsTextDark,
	AWFLayerTypeWindGustsTextLarge,
	AWFLayerTypeWindGustsText,
	AWFLayerTypeWindChill,
	AWFLayerTypeWindChillTextMetric,
	AWFLayerTypeWindChillTextDark,
	AWFLayerTypeWindChillTextLarge,
	AWFLayerTypeWindChillText,
	AWFLayerTypeHeatIndex,
	AWFLayerTypeHeatIndexTextMetric,
	AWFLayerTypeHeatIndexTextDark,
	AWFLayerTypeHeatIndexTextLarge,
	AWFLayerTypeHeatIndexText,
	AWFLayerTypeFeelsLike,
	AWFLayerTypeFeelsLikeTextMetric,
	AWFLayerTypeFeelsLikeTextDark,
	AWFLayerTypeFeelsLikeTextLarge,
	AWFLayerTypeFeelsLikeText,
	AWFLayerTypePrecip1Hour,
	AWFLayerTypePrecip1Day,
	AWFLayerTypePrecip7Day,
	AWFLayerTypePrecip14Day,
	AWFLayerTypePrecip30Day,
	AWFLayerTypePrecip60Day,
	AWFLayerTypePrecip90Day,
	AWFLayerTypePrecipMTD,
	AWFLayerTypePrecipYTD,
	AWFLayerTypePrecipWYTD,
	AWFLayerTypePrecip,
	AWFLayerTypeCloudCover,
	AWFLayerTypeSnowDepth,
	AWFLayerTypeSnowDepthGlobal,
	AWFLayerTypeVisibility,
	
	// outlooks
	AWFLayerTypeFiresDryltgOutlook,
	AWFLayerTypeTemperaturesOutlook6To10Day,
	AWFLayerTypePrecipOutlook6To10Day,
	AWFLayerTypeTemperaturesOutlook8To14Day,
	AWFLayerTypePrecipOutlook8To14Day,
	
	// ocean
	AWFLayerTypeChlorophyll,
	AWFLayerTypeSeaSurfaceTemps,
	
	// roads
	AWFLayerTypeRoadConditions,
	
	// point
	AWFLayerTypeStormCells,
	AWFLayerTypeStormReports,
	AWFLayerTypeLightningStrikes,
	AWFLayerTypeFires,
	AWFLayerTypeRecords,
	AWFLayerTypeRivers,
	AWFLayerTypeEarthquakes,
	
	// polygons
	AWFLayerTypeWarnings,
	AWFLayerTypeConvectiveOutlook,
	AWFLayerTypeFireOutlook,
	AWFLayerTypeDroughtIndex,
	
	AWFLayerTypeObservation
};
